# Generated by Django 5.1.1 on 2024-12-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='foods.food'),
            preserve_default=False,
        ),
    ]
