# Generated by Django 5.1.4 on 2024-12-29 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.destination'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'destination', 'interaction_type'], name='recommendat_user_id_a917bf_idx'),
        ),
    ]
